config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get "sessions/create"
  get "sessions/destroy"

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pragprog Books Online Store
    = stylesheet_link_tag    "application", media: "all",
      "data-turbolinks-track" => true                     
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        .navbar-header
          = @page_title || t('.title')
          %a.navbar-brand{:href => "#"}
            = image_tag("logo.png") 
          %ul.nav.navbar-nav.navbar-right
            %li
              = form_tag store_path, class: 'locale' do
                = select_tag 'set_locale',                        
                  options_for_select(LANGUAGES, I18n.locale.to_s),onchange: 'this.form.submit()', class: "form-control"                  
                = submit_tag 'submit'
                = javascript_tag "$('.locale input').hide()"           
            %li
              %a{:href => "#"}
                %span.glyphicon.glyphicon-log-in
                Login
    .container-fluid.text-center
      .row.content
        .col-sm-2.sidenav
          - if @cart
            = hidden_div_if(@cart.line_items.empty?, id: 'cart') do
              = render @cart
          %p
            %a{:href => "http://www...."}= t('.home')
          %p
            %a{:href => "http://www..../faq"}= t('.questions')
          %p
            %a{:href => "http://www..../news"}= t('.news')
          %p
            %a{:href => "http://www..../contact"}= t('.contact')
          - if session[:user_id]
            %p
              = link_to 'Orders',   orders_path
            %p
              = link_to 'Products', products_path
            %p
              = link_to 'Users',    users_path
            %p
              = button_to 'Logout', logout_path, method: :delete, class: "btn btn-default"
        .col-sm-8.text-left
          = yield
        .col-sm-2.sidenav
          .well
            %p ADS
          .well
            %p ADS
    %footer.container-fluid.text-center
      %p Footer Text

   
        